### Örnek Teorisi

In [1]:
import numpy as np

In [2]:
population = np.random.randint(0,80,(10000))

In [3]:
population[0:10]

array([22, 34, 37, 57, 52, 41, 12, 78, 75, 78])

#### Örneklem Çekimi 

In [4]:
np.random.seed(10)

In [5]:
sample = np.random.choice(a=population,size=100)

In [6]:
sample[0:10]

array([ 6, 12,  8, 36, 61,  8, 66, 58, 69, 21])

In [7]:
sample.mean()

39.89

In [8]:
population.mean()

39.6632

In [12]:
samples = np.array([ np.random.choice(a=population,size=100).mean() for i in range(10)])

In [13]:
samples

array([40.94, 37.08, 38.61, 41.71, 41.3 , 39.44, 38.13, 39.88, 43.59,
       39.64])

In [15]:
np.mean(samples)

40.032

In [20]:
samples[0]

40.94

### Betimsel İstatistikler

In [21]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [22]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [23]:
!pip install researchpy as rp
import researchpy as rp

     |████████████████████████████████| 3.7 MB 787 kB/s eta 0:00:01
  Created wheel for rp: filename=rp-0.1.574-py3-none-any.whl size=2440344 sha256=2d9f5122a0d0efc28933eb5c73511a6c2974d4498ec35bc143395756b99f54b9
  Stored in directory: /home/muhammed/.cache/pip/wheels/d8/04/f5/dfa0d9417530d0817b514041b792c9a801903fc91a74d9dc30
  Created wheel for doge: filename=doge-3.5.0-py3-none-any.whl size=16562 sha256=1def440c853562c3eff838cdfc2010d74169fadcc51d9b498c799baf76501b71
  Stored in directory: /home/muhammed/.cache/pip/wheels/ea/fc/5f/0d6b5816352c4beb582d6c29e76d3fb90fcd5d233b830b7b0d
Successfully built rp doge


In [30]:
numeric_df = df[df.select_dtypes(include=["int64","float64"]).columns]
categorical_df = df[df.select_dtypes(include=["category"]).columns]

In [31]:
rp.summary_cont(numeric_df)

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [32]:
rp.summary_cat(categorical_df)

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79
8     time  Dinner    176    72.13
9            Lunch     68    27.87

In [37]:
numeric_df.cov() # Kovaryans : iki değişkenin ilişkisini değişim ölçüsü

total_bill       tip      size
total_bill   79.252939  8.323502  5.065983
tip           8.323502  1.914455  0.643906
size          5.065983  0.643906  0.904591

In [38]:
numeric_df.corr() # Korelasyon : iki değişken arasındaki ilişkinin doğruluğunu gösterir.

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

### Güven Aralığı 

    * Default olarak %95 alınır. Z tablosundaki karşılığı 1.96 dır.
    * 1.Örneklem boyutu , ortalama , standart sapma bulunur.
    * Güven aralığı 95 mi 99 mu olacak ?
    * Formülü : x +- z x s/square(n)

### İş uygulaması : Fiyat Stratejisi Karar Destek Sistemi
    * Problem : CEO fiyat belirleme konusunda bilimsel bir dayanak ve esneklik istiyor.

In [40]:
prices = np.random.randint(10,110,(1000))

In [42]:
np.mean(prices)

60.3

In [43]:
import statsmodels.stats.api as sms

In [44]:
sms.DescrStatsW(prices).tconfint_mean()

(58.521939954074355, 62.07806004592564)