# PANDAS 

In [6]:
import pandas as pd
import numpy as np

In [7]:
pd.Series(np.array([1,2,3,4,5]))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
ülkeler = np.array(["abd","çin","türkiye","fransa"])

In [19]:
seri = pd.Series(ülkeler)
seri

0        abd
1        çin
2    türkiye
3     fransa
dtype: object

In [14]:
pd.Series(ülkeler == "abd")

0     True
1    False
2    False
3    False
dtype: bool

In [15]:
gelir={"abd":80000,"almanya":50000,"türkiye":150000}

In [24]:
gelir = pd.Series(gelir)

In [22]:
seri.values

array(['abd', 'çin', 'türkiye', 'fransa'], dtype=object)

In [28]:
seri.index

RangeIndex(start=0, stop=4, step=1)

In [27]:
gelir.index

Index(['abd', 'almanya', 'türkiye'], dtype='object')

In [29]:
gelir.values

array([ 80000,  50000, 150000])

In [30]:
seri.dtype

dtype('O')

In [31]:
seri.shape

(4,)

In [32]:
gelir.shape

(3,)

In [35]:
gelir.name = "Gelirler"
gelir.head()

abd         80000
almanya     50000
türkiye    150000
Name: Gelirler, dtype: int64

### Paramtreler ve Argümanlar

In [36]:
yıllar = np.array([2015,2016,2017,2018])
gelir = np.array([10000,20000,30000,40000])

In [41]:
seri = pd.Series(data=gelir,index=yıllar)
seri.name = "Gelirler"
seri

2015    10000
2016    20000
2017    30000
2018    40000
Name: Gelirler, dtype: int64

In [42]:
sayı = [1,2,4,6,8,3,34]

In [45]:
sayı = pd.Series(sayı)
sayı

0     1
1     2
2     4
3     6
4     8
5     3
6    34
dtype: int64

In [46]:
sayı.sum()

58

In [47]:
sayı.min()

1

In [48]:
sayı.product()

39168

In [49]:
sayı.mean()

8.285714285714286

In [50]:
np.mean(sayı.values)

8.285714285714286

### Read_csv head ve tail

In [54]:
cars = {'Brand': ['Honda Civic','Toyota Corolla','Ford Focus','Audi A4'],
        'Price': [22000,25000,27000,35000]
        }

df = pd.DataFrame(cars, columns= ['Brand', 'Price'])
df.to_csv (r'export_dataframe.csv', index = False, header=True)
df

Brand  Price
0     Honda Civic  22000
1  Toyota Corolla  25000
2      Ford Focus  27000
3         Audi A4  35000

In [58]:
cars = pd.read_csv("export_dataframe.csv",)

In [56]:
pd.Series(np.arange(10)).to_csv(r'ülke.csv',index=False,header=True)

In [57]:
pd.read_csv("ülke.csv")

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7
8  8
9  9

In [64]:
cars = pd.read_csv("export_dataframe.csv",squeeze=True)
cars

Brand  Price
0     Honda Civic  22000
1  Toyota Corolla  25000
2      Ford Focus  27000
3         Audi A4  35000

In [65]:
cars.head(2)

Brand  Price
0     Honda Civic  22000
1  Toyota Corolla  25000

In [66]:
cars.tail(2)

Brand  Price
2  Ford Focus  27000
3     Audi A4  35000

### Built in Function 

In [69]:
cars = pd.read_csv("export_dataframe.csv",squeeze=True)

In [72]:
type(cars)
cars

Brand  Price
0     Honda Civic  22000
1  Toyota Corolla  25000
2      Ford Focus  27000
3         Audi A4  35000

In [79]:
len(cars)

4

In [82]:
type(cars["Brand"])

pandas.core.series.Series

In [86]:
sorted(cars["Brand"])

['Audi A4', 'Ford Focus', 'Honda Civic', 'Toyota Corolla']

In [90]:
min(cars["Price"])

22000

### SORT_VALUE , INPLACE , IN

In [97]:
brands = cars["Brand"].copy()

In [99]:
brands.sort_values(ascending=False,inplace=True)
brands

1    Toyota Corolla
0       Honda Civic
2        Ford Focus
3           Audi A4
Name: Brand, dtype: object

In [100]:
brands.sort_index()

0       Honda Civic
1    Toyota Corolla
2        Ford Focus
3           Audi A4
Name: Brand, dtype: object

In [104]:
"Audi A4" in brands.values

True

### Indeksleme ve Matematiksel İşlemler

In [105]:
brands[:-1]

1    Toyota Corolla
0       Honda Civic
2        Ford Focus
Name: Brand, dtype: object

In [106]:
prices = cars["Price"].copy()

In [107]:
prices

0    22000
1    25000
2    27000
3    35000
Name: Price, dtype: int64

In [108]:
prices.count()

4

In [111]:
prices.values

array([22000, 25000, 27000, 35000])

In [112]:
prices.sum()

109000

In [113]:
prices.mean()

27250.0

In [114]:
np.mean(prices.values)

27250.0

In [115]:
np.std(prices.values)

4815.340071064556

In [117]:
np.min(prices.values)
#or prices.min()

22000

In [118]:
prices.median()

26000.0

In [119]:
prices.describe()

count        4.000000
mean     27250.000000
std       5560.275773
min      22000.000000
25%      24250.000000
50%      26000.000000
75%      29000.000000
max      35000.000000
Name: Price, dtype: float64

# value_count , idxmax() , idxmin() ve apply metodları

In [121]:
brands

1    Toyota Corolla
0       Honda Civic
2        Ford Focus
3           Audi A4
Name: Brand, dtype: object

In [122]:
cars.index

RangeIndex(start=0, stop=4, step=1)

In [125]:
for i in cars.values.flat:
    print(i)

Honda Civic
22000
Toyota Corolla
25000
Ford Focus
27000
Audi A4
35000


In [127]:
brands.value_counts()

Ford Focus        1
Honda Civic       1
Toyota Corolla    1
Audi A4           1
Name: Brand, dtype: int64

In [129]:
brands.value_counts(ascending=True)

Audi A4           1
Toyota Corolla    1
Honda Civic       1
Ford Focus        1
Name: Brand, dtype: int64

In [130]:
prices.max()

35000

In [131]:
prices.idxmax()

3

In [132]:
prices[prices.idxmax()]

35000

In [136]:
prices[0:2].values

array([22000, 25000])

In [140]:
type(prices[0:1])

pandas.core.series.Series

In [141]:
type(prices[0])

numpy.int64

In [165]:
prices.apply(lambda x: x/2)

0    11000.0
1    12500.0
2    13500.0
3    17500.0
Name: Price, dtype: float64